### ISSUE TITLE
Error while runing

### ISSUE THREAD

**Issue by pratik-dani** [mrtolkien/fastapi_simple_security#1]
I was trying to run the sample code in the Readme. I got an error

```
Traceback (most recent call last):
  File "pdfkitv2.py", line 8, in <module>
    from fastapi_simple_security import api_key_router, api_key_security
  File "D:\enviorments\pdfkit\lib\site-packages\fastapi_simple_security\__init__.py", line 1, in <module>
    from fastapi_simple_security.endpoints import api_key_router
  File "D:\enviorments\pdfkit\lib\site-packages\fastapi_simple_security\endpoints.py", line 7, in <module>
    from fastapi_simple_security._security_secret import secret_based_security
  File "<fstring>", line 1
    (SECRET=)
```

I think there is an error in the file _security_secret.py Line 18.

**Comment by mrtolkien** [comment]
Which python version or you using?

It seems it might be linked to your python version not being able to use f-strings with =, which were an addition of python 3.8

**Comment by pratik-dani** [comment]
Okay. My python version is 3.7. I think this might be the issue.

**Comment by pratik-dani** [comment]
Hi I upgraded the python I am now using 3.8.5. But after running I am getting this error now.

`sqlite3.OperationalError: unable to open database file`

**Comment by tordnilsen** [comment]
Hi. I also have same error. My version is 3.9.1, running on wsl2
