### ISSUE TITLE
Reopen #11: loosen pip requirements on fastAPI...

### ISSUE THREAD

**Issue by plocher** [mrtolkien/fastapi_simple_security#12]
when using pip (and not poetry...) the error is

The conflict is caused by:
- The user requested fastapi==0.75.2
-  fastapi-simple-security 1.0.1 depends on fastapi<0.71 and >=0.70

From the package on pypi

fastapi_simple_security-1.0.1.dist-info/METADATA:Requires-Dist: fastapi (>=0.70,<0.71)
The only other ref to fastapi in your repo is

[[package]]
name = "fastapi"
version = "0.70.0"
description = "FastAPI framework, high performance, easy to learn, fast to code, ready for production"
category = "main"
optional = false
python-versions = ">=3.6.1"

**Comment by mrtolkien** [comment]
Should be good.
