### ISSUE TITLE
Replace uuid4() to generate API keys

### ISSUE THREAD

**Issue by simon-lund** [mrtolkien/fastapi_simple_security#29]
Hello,

I was just looking through fastapi security/auth libraries and I saw that in this library, api keys and also the secret value is created with uuid4(). However, UUID is not secure for that purpose and should not be used according to [RFC4122](https://datatracker.ietf.org/doc/html/rfc4122#section-6). Instead, use something like `token_urlsafe` from the [secrets package](https://docs.python.org/3/library/secrets.html).

https://github.com/mrtolkien/fastapi_simple_security/blob/c2db8d70795a2cac682f759296206122df64b5fb/fastapi_simple_security/_sqlite_access.py#L58

**Comment by mrtolkien** [comment]
You're welcome to make a PR for this.
