### ISSUE TITLE
Access api key from function

### ISSUE THREAD

**Issue by rehmatworks** [mrtolkien/fastapi_simple_security#3]
Thank you for this great library. I have a question. Is there a way to access the API key that was used to request a secure endpoint when the dependency is used globally? For example:

```python
app.include_router(myrouter, prefix='/myrouter', dependencies=[Depends(api_key_security)])

@myrouter.get('/secured-endpoint/')
async def secured_endpoint():
    return {'key': 'api-key'}
```

Does the request state contain the API key or it isn't passed anywhere? If the key isn't available in any context, we will have to use the dependency in each function like this:

```python
from fastapi.security.api_key import APIKey


@app.get('/secured-endpoint/')
async def secured_endpoint(api_key: APIKey = Depends(api_key_security)):
    return {'key': api_key}
```

Please let me know if there's a possibility to use the dependency globally on a router and still get the API key value in all sub-routes.

**Comment by rehmatworks** [comment]
I am not sure either I am doing this correctly or not, but here is what I am doing in order to access API key for each request. If this isn't needed and if the library already provided the associated key somewhere, please let me know.

```python
# Handle API requests <--> api key association
@app.middleware('http')
async def add_api_key(request: Request, call_next):
    if request.headers.get('api_key'):
        api_key = request.headers.get('api_key')
    else:
        api_key = request.query_params.get('api_key')
    request.state.api_key = api_key
    response = await call_next(request)
    return response
```

**Comment by mrtolkien** [comment]
Accessing the `Request` object is indeed the right approach at is holds the relevant information.

My own library here is very basic and does not have anything past the dependency itself.
