### ISSUE TITLE
typo error in _security_secret.py

### ISSUE THREAD

**Issue by bijonguha** [mrtolkien/fastapi_simple_security#9]
warnings.warn(
         f"ENVIRONMENT VARIABLE 'FASTAPI_SIMPLE_SECURITY_SECRET' NOT FOUND\n"
         f"\tGenerated a single-use secret key for this session:\n"
         f"\t{SECRET=}"
 )

**Comment by mrtolkien** [comment]
Could you be a bit clearer as to what the typo is?
